config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  put 'admin/update/:id' => 'admin#update'
  patch 'admin/udpate/:id' => 'admin#update'

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  resources :users
  resources :apartments do
    get 'map_location'
  end

  root 'apartments#index'

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  validates :address1, presence: true
  validates :address2, presence: true
  validates :city, presence: true
  validates :postal_code, presence: true
  validates :state, presence: true
  validates :country, presence: true
  validates :user, presence: true

  geocoded_by :full_address
  after_validation :geocode

  belongs_to :user
  resourcify

  def full_address
    @full_address = address1 + ", " + address2 + ", " + city + ", " + postal_code + ", " + state + ", " + country
  end
  #add paperclip
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment :image, presence: true,
    content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
    size: { in: 0..10.megabytes }
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource

  # GET /apartments
  # GET /apartments.json
  def index
    if params[:search].nil?
      @apartments = Apartment.all
    else
      @apartments = Apartment.search(params[:search])
    end


    @pindrop = Gmaps4rails.build_markers(@apartments) do |apartment, marker|
      marker.lat apartment.latitude
      marker.lng apartment.longitude
      marker.infowindow apartment.full_address
    end
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
    @apartments = Apartment.find(params[:id]) #@apartments may also be found using the set_apartment method provided by scaffolding
    @pindrop = Gmaps4rails.build_markers(@apartments) do |apartment, marker|
      marker.lat apartment.latitude
      marker.lng apartment.longitude
      marker.infowindow apartment.full_address
    end
  end

  def map_location
    @apartment = Apartment.find(params[:apartment_id])
    @hash = Gmaps4rails.build_markers(@apartment) do |apartment, marker|
      marker.lat apartment.latitude
      marker.lng apartment.longitude
      marker.infowindow apartment.full_address
    end
    render json: @hash.to_json
  end


  # GET /apartments/new
  def new
    # @apartment = Apartment.new
    @apartment = current_user.apartments.build
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = current_user.apartments.build(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:latitude, :longitude, :address1, :address2, :city, :postal_code, :state, :country, :image,  :owner_name, :contact_time, :owner_phone, :search)
    end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/views/apartments/_form.html.erb
<%= form_for(@apartment, html: { class: "form-horizontal", role: "form", multipart: true }) do |f| %>
  <% if @apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <% @apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--<div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>-->
  <div class="form-group">
    <%= f.label :address1, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address1, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address2, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address2, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :city, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :city, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :postal_code, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :postal_code, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :state, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :state, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :country, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :country, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :image, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :owner_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :owner_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :contact_time, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :contact_time, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :owner_phone, class: "col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.text_field :owner_phone, class: "form-control" %>
    </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: "btn btn-primary" %>
  </div>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>

<%= render 'form' %>

<%= link_to 'Show', @apartment, :class => "btn btn-xs btn-primary" %> |
<%= link_to 'Back', apartments_path, :class => "btn btn-xs btn-primary" %>

app/views/apartments/index.html.erb
<!--<p id="notice"><%= notice %></p>-->

<h1 class="text-center">Welcome to Apartment Finder!</h1>

<div class="row">
  <form action="/" method="get" class="form-inline text-right">
    <div class="col-sm-4 col-sm-offset-8">
      <div class="form-group">
        <input type="text" name="search" class="form-control">
        <input type="submit" value="Search" class="btn btn-primary btn-sm">
      </div>
    </div>
  </form>
</div>
<hr>

<table class="table">
  <thead>
    <tr>
      <!--<th>Latitude</th>-->
      <!--<th>Longitude</th>-->
      <th>Address1</th>
      <th>Address2</th>
      <th>City</th>
      <th>Postal code</th>
      <th>State</th>
      <th>Country</th>
      <th>Owner name</th>
      <th>Contact time</th>
      <th>Owner phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <!--<td><%= apartment.latitude %></td>-->
        <!--<td><%= apartment.longitude %></td>-->
        <td><%= apartment.address1 %></td>
        <td><%= apartment.address2 %></td>
        <td><%= apartment.city %></td>
        <td><%= apartment.postal_code %></td>
        <td><%= apartment.state %></td>
        <td><%= apartment.country %></td>
        <td><%= apartment.owner_name %></td>
        <td><%= apartment.contact_time %></td>
        <td><%= apartment.owner_phone %></td>
        <td><%= link_to 'Show', apartment, :class => "btn btn-xs btn-success" %></td>
        <% if !current_user.nil? && (apartment.user == current_user || current_user.has_role?(:admin)) %>
          <td><%= link_to 'Edit', edit_apartment_path(apartment), :class => "btn btn-xs btn-warning" %></td>
          <td><%= link_to 'Destroy', apartment, :class => "btn btn-xs btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<div id="allmap"></div>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({
    provider: {},
    internal: {id: 'allmap'}
  },
  function() {
    markers = handler.addMarkers(<%=raw @pindrop.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(12);
  }
);
</script>

<br>

<%= link_to 'New Apartment', new_apartment_path, :class => "btn btn-primary" %>

<%= link_to 'Sign Up', new_user_registration_path, :class => "btn btn-primary" %>

<%= link_to 'Sign In', new_user_session_path, :class => "btn btn-primary" %>

<!--<#%= link_to 'Sign in with Twitter', user_omniauth_authorize_path(:twitter) %>-->

app/views/apartments/new.html.erb
<h1>New Apartment</h1>

<%= render 'form' %>

<%= link_to 'Back', apartments_path, :class => "btn btn-xs btn-primary" %>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @apartment.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @apartment.longitude %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @apartment.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @apartment.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @apartment.city %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @apartment.postal_code %>
</p>

<p>
  <strong>State:</strong>
  <%= @apartment.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @apartment.country %>
</p>

<p>
  <strong>Owner name:</strong>
  <%= @apartment.owner_name %>
</p>

<p>
  <strong>Contact time:</strong>
  <%= @apartment.contact_time %>
</p>

<p>
  <strong>Owner phone:</strong>
  <%= @apartment.owner_phone %>
</p>

<%= link_to image_tag(@apartment.image.url(:large)), @apartment.image.url %>

<%= link_to 'Edit', edit_apartment_path(@apartment), :class => "btn btn-xs btn-primary" %> |
<%= link_to 'Back', apartments_path, :class => "btn btn-xs btn-primary" %>

<div id="map" data-apartment-id="<%=@apartment.id%>"></div>